server:
    port: 9002
    context-path:

spring:
    datasource:
        url: jdbc:mysql://192.168.25.71:3306/test_activiti_wql?characterEncoding=UTF-8
        username: kislev_admin
        password: HYyWPe1gFJ5dVo2b7xA5PON6ZHdMpLw
        driver-class-name: com.mysql.jdbc.Driver


#暂时不考虑多实例服务,thrift server config
thrift:
  server:
    port: 8094
    thriftInterface: com.ws.shavuot.thrift.workflow.WorkflowService #thirft 接口
    selectorThreadCount: 2 #处理网络IO线程池大小, 默认为2
    workerThreadCount: 5 #处理请求线程池大小,默认为5
    acceptQueueSizePerThread: 4 #每个selector thread等待队列长度,默认4

  client1:
      host: 127.0.0.1
      port: 8094
      timeout: 60000 # 超时时间
      maxIdle: 3 #最大空闲连接数,默认值 8
      maxTotal: 10 #最大连接数, 默认值 8
      minIdle: 3 #最小空闲连接数, 默认值 0
