server:
    port: 9001
    context-path:


spring:
    jackson.serialization.INDENT_OUTPUT: true
    profiles.active: local


---
spring:
    profiles: local

    datasource:
        name: shavuot
        url: jdbc:mysql://192.168.25.71:3306/shavuot?characterEncoding=UTF-8
        username: kislev_admin
        password: HYyWPe1gFJ5dVo2b7xA5PON6ZHdMpLw
        driver-class-name: com.mysql.jdbc.Driver


#配置thrift
thrift:
  #连接shavuot-workflow
  client1:
      host: 127.0.0.1
      port: 8094
      timeout: 60000 # 超时时间
      maxIdle: 3 #最大空闲连接数,默认值 8
      maxTotal: 10 #最大连接数, 默认值 8
      minIdle: 3 #最小空闲连接数, 默认值 0
